# R Matrices

## Matrices
* **A matrix is a two dimensional data set with columns and rows.**
* **A column is a vertical representation of data, while a row is a horizontal representation of data.**
>A matrix can be created with the `matrix()` function. Specify the `nrow` and `ncol` parameters to get the amount of rows and columns:

In [1]:
# Create a matrix
thismatrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2)

# Print the matrix
thismatrix

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

Note: Remember the `c()` function is used to concatenate items together.

In [3]:
# You can also create a matrix with strings:

thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix

[,1]   [,2]  
[1,] apple  cherry
[2,] banana orange

## Access Matrix Items
You can access the items by using `[ ]` brackets. The first number "1" in the bracket specifies the row-position, while the second number "2" specifies the column-position:

In [4]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[1, 2]

[1] "cherry"

The whole row can be accessed if you specify a comma after the number in the bracket:

In [6]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[2,]

[1] "banana" "orange"

The whole column can be accessed if you specify a comma before the number in the bracket:

In [7]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[,2]

[1] "cherry" "orange"

## Access More Than One Row
More than one row can be accessed if you use the `c()` function:

In [8]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix[c(1,2),]

[,1]   [,2]   [,3] 
[1,] apple  orange pear 
[2,] banana grape  melon

## Access More Than One Column
More than one column can be accessed if you use the `c()` function:

In [9]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix[, c(1,2)]

[,1]   [,2]     
[1,] apple  orange   
[2,] banana grape    
[3,] cherry pineapple

## Add Rows and Columns
Use the `cbind()` function to add additional columns in a Matrix:

In [10]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

newmatrix <- cbind(thismatrix, c("strawberry", "blueberry", "raspberry"))

# Print the new matrix
newmatrix

[,1]   [,2]      [,3]  [,4]      
[1,] apple  orange    pear  strawberry
[2,] banana grape     melon blueberry 
[3,] cherry pineapple fig   raspberry

**Note:** The cells in the new column must be of the same length as the existing matrix.

Use the `rbind()` function to add additional rows in a Matrix:

In [12]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

newmatrix <- rbind(thismatrix, c("strawberry", "blueberry", "raspberry"))

# Print the new matrix
newmatrix

[,1]       [,2]      [,3]     
[1,] apple      orange    pear     
[2,] banana     grape     melon    
[3,] cherry     pineapple fig      
[4,] strawberry blueberry raspberry

**Note:** The cells in the new row must be of the same length as the existing matrix.

## Remove Rows and Columns
Use the `c()` function to remove rows and columns in a Matrix:

In [15]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "mango", "pineapple"), nrow = 3, ncol =2)

#Remove the first row and the first column
thismatrix <- thismatrix[-c(1), -c(1)]

thismatrix

[1] "mango"     "pineapple"

## Check if an Item Exists
To find out if a specified item is present in a matrix, use the `%in%` operator:

In [16]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

"apple" %in% thismatrix

[1] TRUE

## Amount of Rows and Columns
Use the `dim()` function to find the amount of rows and columns in a Matrix:

In [17]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

dim(thismatrix)

[1] 2 2

## Matrix Length
Use the `length()` function to find the dimension of a Matrix:

In [18]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

length(thismatrix)

[1] 4

Total cells in the matrix is the number of rows multiplied by number of columns.

In the example above: Dimension = 2*2 = 4.

## Loop Through a Matrix
You can loop through a Matrix using a `for` loop. The loop will start at the first row, moving right:

In [19]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

for (rows in 1:nrow(thismatrix)) {
  for (columns in 1:ncol(thismatrix)) {
    print(thismatrix[rows, columns])
  }
}

[1] "apple"
[1] "cherry"
[1] "banana"
[1] "orange"


## Combine two Matrices
Again, you can use the `rbind()` or `cbind()` function to combine two or more matrices together:

In [20]:
# Combine matrices
Matrix1 <- matrix(c("apple", "banana", "cherry", "grape"), nrow = 2, ncol = 2)
Matrix2 <- matrix(c("orange", "mango", "pineapple", "watermelon"), nrow = 2, ncol = 2)

# Adding it as a rows
Matrix_Combined <- rbind(Matrix1, Matrix2)
Matrix_Combined

# Adding it as a columns
Matrix_Combined <- cbind(Matrix1, Matrix2)
Matrix_Combined

[,1]   [,2]      
[1,] apple  cherry    
[2,] banana grape     
[3,] orange pineapple 
[4,] mango  watermelon

[,1]   [,2]   [,3]   [,4]      
[1,] apple  cherry orange pineapple 
[2,] banana grape  mango  watermelon

# Thank You